encoder_class: KmerSequenceEncoder
encoder_parameters:
  kmer_length: 3
  site_count: 500
model_class: JoinedRSCNNModel
model_hyperparameters:
  dropout_prob: 0.3
  embedding_dim: 7
  filter_count: 19
  kernel_size: 11
  kmer_length: 3
serialization_version: 0
training_hyperparameters:
  learning_rate: 0.001
  min_learning_rate: 1.0e-06
  weight_decay: 1.0e-06
